@baseUrl = http://localhost:5000
@tenantId = 00000000-0000-0000-0000-000000000001
@accessToken = {{token}}

### Get Audits (Paged)
GET {{baseUrl}}/audit?pageIndex=1&pageSize=10
Authorization: Bearer {{accessToken}}
X-Tenant-Id: {{tenantId}}
